{
 "title": "gem5demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "system.cpu.branchPred.BTBHitRatio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"system.cpu.branchPred.BTBHitRatio\")"
    }
   ]
  },
  {
   "title": "system.cpu.branchPred.BTBHits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"system.cpu.branchPred.BTBHits\")"
    }
   ]
  },
  {
   "title": "system.cpu.branchPred.condIncorrect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"system.cpu.branchPred.condIncorrect\")"
    }
   ]
  },
  {
   "title": "system.cpu.branchPred.condPredicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"system.cpu.branchPred.condPredicted\")"
    }
   ]
  },
  {
   "title": "system.cpu.branchPred.indirectHits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"system.cpu.branchPred.indirectHits\")"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"demo\")\r\n                |> range(start: -2d)\r\n                |> filter(fn: (r) => r[\"_measurement\"] == \"gem5template\")\r\n                |> filter(fn: (r) => r[\"_field\"] == \"\")"
    }
   ]
  }
 ]
}